version: "3.9"

services:
  splash-backend:
    build: .
    container_name: splash-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:4.4.18
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
